# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jsdoc-toolkit}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ggironda"]
  s.date = %q{2009-10-06}
  s.description = %q{RubyGem packaged version of jsdoc-toolkit with extra rake tasks for automating doc generation}
  s.email = %q{gabriel.gironda@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".gitmodules",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/jsdoc-toolkit.rb",
     "lib/jsdoc-toolkit/doc_task.rb",
     "lib/jsdoc-toolkit/generator.rb",
     "test/doc_task_test.rb",
     "test/generator_test.rb",
     "test/input/bar/foo.js",
     "test/input/test.js",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/gabrielg/jsdoc-toolkit}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "test/doc_task_test.rb",
     "test/generator_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0"])
    else
      s.add_dependency(%q<riot>, [">= 0"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0"])
  end
end
